### PR TITLE
Add ez-configs

### PR DESCRIPTION
**Pull request by ehllie**
I've ran `nix flake check` locally and it passed. A nice addition would be either having a package output that lets you host the rendered website on localhost to preview changed with something as simple as `nix run .#pkgName`, or including documentation on how to do that if already present, cause I can't really see how to do that conveniently at a glance.

### CODE REVIEW

**Comment by roberth** [comment]
bors try

**Comment by ehllie** [comment]
Ok, `nix flake check` only passes now. Turns out that I hadn't actually included included my flake in `perSystem.render.inputs` in the first version of the PR, and that's why it had passed originally 🙃

**Comment by roberth** [comment]
Thanks!

> bors try

Looks like I got spoiled by ofborg without @

@bors r+

**Comment by roberth** [comment]
Wait, no, that's not it. Maybe it's discontinued now. Ok, this setup will need some work later.

**Comment by roberth** [comment]
and it's live at https://flake.parts/options/ez-configs :rocket:

**Pull request merged**
