### PR TITLE
Add pydev

### PR DESCRIPTION
**Pull request by zupo**

### CODE REVIEW

**Comment by zupo** [comment]
`nix flake check` fails locally with the following, I can't figure out why:

```
warning: Git tree '/Users/zupo/work/flake.parts-website' is dirty
evaluating flake...
trace: warning: optionsDocBook is deprecated since 23.11 and will be removed in 24.05
error:
       … while checking flake output 'packages'

         at «none»:0: (source not available)

       … while checking the derivation 'packages.aarch64-darwin.default'

         at «none»:0: (source not available)

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'pydev' missing

       at /nix/store/7kr0izfdjdqh6iswizks55lq8szcjrgl-source/flake-module.nix:3:5:

            2|   imports = [
            3|     inputs.pydev.inputs.pre-commit-hooks-nix.flakeModule
             |     ^
            4|     ./interface.nix
warning: Git tree '/Users/zupo/work/flake.parts-website' is dirty
evaluating flake...
trace: warning: optionsDocBook is deprecated since 23.11 and will be removed in 24.05
error:
       … while checking flake output 'packages'

         at «none»:0: (source not available)

       … while checking the derivation 'packages.aarch64-darwin.default'

         at «none»:0: (source not available)

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'pydev' missing

       at /nix/store/7kr0izfdjdqh6iswizks55lq8szcjrgl-source/flake-module.nix:3:5:

            2|   imports = [
            3|     inputs.pydev.inputs.pre-commit-hooks-nix.flakeModule
             |     ^
            4|     ./interface.nix
```

**Comment by zupo** [comment]
cc @davhau

**Comment by zupo** [comment]
@roberth: fixed pydev upstream, `nix flake check` now passes on my local!

**Comment by Kranzes** [comment]
i am begging, come up with a new name for this :moyai:

**Comment by roberth** [comment]
@Kranzes not sure I see the problem. Do you think it's too general? I've been thinking about perhaps prefixing org names on the site. In that case it'd be oceansprint/pydev. (Still debating because idk if readability suffers too much)

**Comment by Kranzes** [comment]
I think its way too general and also there's another software with that name that already exists.

**Comment by DavHau** [comment]
> I  think its way too general

Perfect, that means the name nails it, because it is supposed to be a very general flake for all kinds of python projects.

> software with that name already exists

If of the author(s) of the other pydev software will ever want to add it to flake-parts, then we can still debate in re-naming the entry to 'oceansprint-pydev' or 'nix-pydev' or whatever.

Let's move on from the bike shedding.
If you are serious in finding a better name, please open an issue upstream at oceansprint/pydev to continue discussion there. And please include a suggestion of a better name, otherwise this is little more than trolling.

**Comment by roberth** [comment]
These names aren't identifiers, so it's not a big deal. Let's keep it simple. I'll be happy to rename the page later.

**Comment by roberth** [comment]
... and it's live at <https://flake.parts/options/pydev>!

Thanks @zupo!


Would be nice to have `example` values in the options btw, and a more complete README in the repo, with perhaps a link to a real world example?

**Comment by zupo** [comment]
Thanks! 

Yep, I'll extend the README!

**Pull request merged**
